###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Hamari adhoori kahani2",
    "author": "Benjamin franklin",
    "url": "www.google.com",
    "likes": 20

}
###
GET http://localhost:3003/api/blogs/